// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace RSO.Core.AdModels;

public partial class AdServicesRSOContext : DbContext
{
    public AdServicesRSOContext(DbContextOptions<AdServicesRSOContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Ad> ads { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Ad>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("ad_pkey");

            entity.Property(e => e.ID).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}